/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as PutawayRouteImport } from './routes/putaway'
import { Route as OutboundRouteImport } from './routes/outbound'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as MoveRouteImport } from './routes/move'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksTaskNoRouteImport } from './routes/tasks.$taskNo'
import { Route as PalletPrintBatchRouteImport } from './routes/pallet.print-batch'
import { Route as PalletCreateRouteImport } from './routes/pallet.create'
import { Route as PalletPalletIdRouteImport } from './routes/pallet.$palletId'
import { Route as MobileTasksRouteImport } from './routes/mobile.tasks'
import { Route as MobileScanPutawayRouteImport } from './routes/mobile.scan-putaway'
import { Route as MobileScanPickRouteImport } from './routes/mobile.scan-pick'
import { Route as MobileScanMoveRouteImport } from './routes/mobile.scan-move'
import { Route as MobileScanLogRouteImport } from './routes/mobile.scan-log'
import { Route as MobileLookupPalletRouteImport } from './routes/mobile.lookup-pallet'
import { Route as MobileLookupLocationRouteImport } from './routes/mobile.lookup-location'
import { Route as MasterSkuRouteImport } from './routes/master.sku'
import { Route as MasterLocationRouteImport } from './routes/master.location'
import { Route as MasterBatchRouteImport } from './routes/master.batch'
import { Route as TasksTaskNoPrintRouteImport } from './routes/tasks.$taskNo.print'
import { Route as MasterLocationPrintRouteImport } from './routes/master.location.print'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const PutawayRoute = PutawayRouteImport.update({
  id: '/putaway',
  path: '/putaway',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboundRoute = OutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveRoute = MoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskNoRoute = TasksTaskNoRouteImport.update({
  id: '/$taskNo',
  path: '/$taskNo',
  getParentRoute: () => TasksRoute,
} as any)
const PalletPrintBatchRoute = PalletPrintBatchRouteImport.update({
  id: '/pallet/print-batch',
  path: '/pallet/print-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const PalletCreateRoute = PalletCreateRouteImport.update({
  id: '/pallet/create',
  path: '/pallet/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PalletPalletIdRoute = PalletPalletIdRouteImport.update({
  id: '/pallet/$palletId',
  path: '/pallet/$palletId',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileTasksRoute = MobileTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => MobileRoute,
} as any)
const MobileScanPutawayRoute = MobileScanPutawayRouteImport.update({
  id: '/scan-putaway',
  path: '/scan-putaway',
  getParentRoute: () => MobileRoute,
} as any)
const MobileScanPickRoute = MobileScanPickRouteImport.update({
  id: '/scan-pick',
  path: '/scan-pick',
  getParentRoute: () => MobileRoute,
} as any)
const MobileScanMoveRoute = MobileScanMoveRouteImport.update({
  id: '/scan-move',
  path: '/scan-move',
  getParentRoute: () => MobileRoute,
} as any)
const MobileScanLogRoute = MobileScanLogRouteImport.update({
  id: '/scan-log',
  path: '/scan-log',
  getParentRoute: () => MobileRoute,
} as any)
const MobileLookupPalletRoute = MobileLookupPalletRouteImport.update({
  id: '/lookup-pallet',
  path: '/lookup-pallet',
  getParentRoute: () => MobileRoute,
} as any)
const MobileLookupLocationRoute = MobileLookupLocationRouteImport.update({
  id: '/lookup-location',
  path: '/lookup-location',
  getParentRoute: () => MobileRoute,
} as any)
const MasterSkuRoute = MasterSkuRouteImport.update({
  id: '/master/sku',
  path: '/master/sku',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterLocationRoute = MasterLocationRouteImport.update({
  id: '/master/location',
  path: '/master/location',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterBatchRoute = MasterBatchRouteImport.update({
  id: '/master/batch',
  path: '/master/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskNoPrintRoute = TasksTaskNoPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => TasksTaskNoRoute,
} as any)
const MasterLocationPrintRoute = MasterLocationPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => MasterLocationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/inventory': typeof InventoryRoute
  '/mobile': typeof MobileRouteWithChildren
  '/move': typeof MoveRoute
  '/movements': typeof MovementsRoute
  '/outbound': typeof OutboundRoute
  '/putaway': typeof PutawayRoute
  '/tasks': typeof TasksRouteWithChildren
  '/master/batch': typeof MasterBatchRoute
  '/master/location': typeof MasterLocationRouteWithChildren
  '/master/sku': typeof MasterSkuRoute
  '/mobile/lookup-location': typeof MobileLookupLocationRoute
  '/mobile/lookup-pallet': typeof MobileLookupPalletRoute
  '/mobile/scan-log': typeof MobileScanLogRoute
  '/mobile/scan-move': typeof MobileScanMoveRoute
  '/mobile/scan-pick': typeof MobileScanPickRoute
  '/mobile/scan-putaway': typeof MobileScanPutawayRoute
  '/mobile/tasks': typeof MobileTasksRoute
  '/pallet/$palletId': typeof PalletPalletIdRoute
  '/pallet/create': typeof PalletCreateRoute
  '/pallet/print-batch': typeof PalletPrintBatchRoute
  '/tasks/$taskNo': typeof TasksTaskNoRouteWithChildren
  '/master/location/print': typeof MasterLocationPrintRoute
  '/tasks/$taskNo/print': typeof TasksTaskNoPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/inventory': typeof InventoryRoute
  '/mobile': typeof MobileRouteWithChildren
  '/move': typeof MoveRoute
  '/movements': typeof MovementsRoute
  '/outbound': typeof OutboundRoute
  '/putaway': typeof PutawayRoute
  '/tasks': typeof TasksRouteWithChildren
  '/master/batch': typeof MasterBatchRoute
  '/master/location': typeof MasterLocationRouteWithChildren
  '/master/sku': typeof MasterSkuRoute
  '/mobile/lookup-location': typeof MobileLookupLocationRoute
  '/mobile/lookup-pallet': typeof MobileLookupPalletRoute
  '/mobile/scan-log': typeof MobileScanLogRoute
  '/mobile/scan-move': typeof MobileScanMoveRoute
  '/mobile/scan-pick': typeof MobileScanPickRoute
  '/mobile/scan-putaway': typeof MobileScanPutawayRoute
  '/mobile/tasks': typeof MobileTasksRoute
  '/pallet/$palletId': typeof PalletPalletIdRoute
  '/pallet/create': typeof PalletCreateRoute
  '/pallet/print-batch': typeof PalletPrintBatchRoute
  '/tasks/$taskNo': typeof TasksTaskNoRouteWithChildren
  '/master/location/print': typeof MasterLocationPrintRoute
  '/tasks/$taskNo/print': typeof TasksTaskNoPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/inventory': typeof InventoryRoute
  '/mobile': typeof MobileRouteWithChildren
  '/move': typeof MoveRoute
  '/movements': typeof MovementsRoute
  '/outbound': typeof OutboundRoute
  '/putaway': typeof PutawayRoute
  '/tasks': typeof TasksRouteWithChildren
  '/master/batch': typeof MasterBatchRoute
  '/master/location': typeof MasterLocationRouteWithChildren
  '/master/sku': typeof MasterSkuRoute
  '/mobile/lookup-location': typeof MobileLookupLocationRoute
  '/mobile/lookup-pallet': typeof MobileLookupPalletRoute
  '/mobile/scan-log': typeof MobileScanLogRoute
  '/mobile/scan-move': typeof MobileScanMoveRoute
  '/mobile/scan-pick': typeof MobileScanPickRoute
  '/mobile/scan-putaway': typeof MobileScanPutawayRoute
  '/mobile/tasks': typeof MobileTasksRoute
  '/pallet/$palletId': typeof PalletPalletIdRoute
  '/pallet/create': typeof PalletCreateRoute
  '/pallet/print-batch': typeof PalletPrintBatchRoute
  '/tasks/$taskNo': typeof TasksTaskNoRouteWithChildren
  '/master/location/print': typeof MasterLocationPrintRoute
  '/tasks/$taskNo/print': typeof TasksTaskNoPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/inventory'
    | '/mobile'
    | '/move'
    | '/movements'
    | '/outbound'
    | '/putaway'
    | '/tasks'
    | '/master/batch'
    | '/master/location'
    | '/master/sku'
    | '/mobile/lookup-location'
    | '/mobile/lookup-pallet'
    | '/mobile/scan-log'
    | '/mobile/scan-move'
    | '/mobile/scan-pick'
    | '/mobile/scan-putaway'
    | '/mobile/tasks'
    | '/pallet/$palletId'
    | '/pallet/create'
    | '/pallet/print-batch'
    | '/tasks/$taskNo'
    | '/master/location/print'
    | '/tasks/$taskNo/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/inventory'
    | '/mobile'
    | '/move'
    | '/movements'
    | '/outbound'
    | '/putaway'
    | '/tasks'
    | '/master/batch'
    | '/master/location'
    | '/master/sku'
    | '/mobile/lookup-location'
    | '/mobile/lookup-pallet'
    | '/mobile/scan-log'
    | '/mobile/scan-move'
    | '/mobile/scan-pick'
    | '/mobile/scan-putaway'
    | '/mobile/tasks'
    | '/pallet/$palletId'
    | '/pallet/create'
    | '/pallet/print-batch'
    | '/tasks/$taskNo'
    | '/master/location/print'
    | '/tasks/$taskNo/print'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/inventory'
    | '/mobile'
    | '/move'
    | '/movements'
    | '/outbound'
    | '/putaway'
    | '/tasks'
    | '/master/batch'
    | '/master/location'
    | '/master/sku'
    | '/mobile/lookup-location'
    | '/mobile/lookup-pallet'
    | '/mobile/scan-log'
    | '/mobile/scan-move'
    | '/mobile/scan-pick'
    | '/mobile/scan-putaway'
    | '/mobile/tasks'
    | '/pallet/$palletId'
    | '/pallet/create'
    | '/pallet/print-batch'
    | '/tasks/$taskNo'
    | '/master/location/print'
    | '/tasks/$taskNo/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  InventoryRoute: typeof InventoryRoute
  MobileRoute: typeof MobileRouteWithChildren
  MoveRoute: typeof MoveRoute
  MovementsRoute: typeof MovementsRoute
  OutboundRoute: typeof OutboundRoute
  PutawayRoute: typeof PutawayRoute
  TasksRoute: typeof TasksRouteWithChildren
  MasterBatchRoute: typeof MasterBatchRoute
  MasterLocationRoute: typeof MasterLocationRouteWithChildren
  MasterSkuRoute: typeof MasterSkuRoute
  PalletPalletIdRoute: typeof PalletPalletIdRoute
  PalletCreateRoute: typeof PalletCreateRoute
  PalletPrintBatchRoute: typeof PalletPrintBatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/putaway': {
      id: '/putaway'
      path: '/putaway'
      fullPath: '/putaway'
      preLoaderRoute: typeof PutawayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbound': {
      id: '/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof OutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move': {
      id: '/move'
      path: '/move'
      fullPath: '/move'
      preLoaderRoute: typeof MoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskNo': {
      id: '/tasks/$taskNo'
      path: '/$taskNo'
      fullPath: '/tasks/$taskNo'
      preLoaderRoute: typeof TasksTaskNoRouteImport
      parentRoute: typeof TasksRoute
    }
    '/pallet/print-batch': {
      id: '/pallet/print-batch'
      path: '/pallet/print-batch'
      fullPath: '/pallet/print-batch'
      preLoaderRoute: typeof PalletPrintBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pallet/create': {
      id: '/pallet/create'
      path: '/pallet/create'
      fullPath: '/pallet/create'
      preLoaderRoute: typeof PalletCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pallet/$palletId': {
      id: '/pallet/$palletId'
      path: '/pallet/$palletId'
      fullPath: '/pallet/$palletId'
      preLoaderRoute: typeof PalletPalletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/tasks': {
      id: '/mobile/tasks'
      path: '/tasks'
      fullPath: '/mobile/tasks'
      preLoaderRoute: typeof MobileTasksRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/scan-putaway': {
      id: '/mobile/scan-putaway'
      path: '/scan-putaway'
      fullPath: '/mobile/scan-putaway'
      preLoaderRoute: typeof MobileScanPutawayRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/scan-pick': {
      id: '/mobile/scan-pick'
      path: '/scan-pick'
      fullPath: '/mobile/scan-pick'
      preLoaderRoute: typeof MobileScanPickRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/scan-move': {
      id: '/mobile/scan-move'
      path: '/scan-move'
      fullPath: '/mobile/scan-move'
      preLoaderRoute: typeof MobileScanMoveRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/scan-log': {
      id: '/mobile/scan-log'
      path: '/scan-log'
      fullPath: '/mobile/scan-log'
      preLoaderRoute: typeof MobileScanLogRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/lookup-pallet': {
      id: '/mobile/lookup-pallet'
      path: '/lookup-pallet'
      fullPath: '/mobile/lookup-pallet'
      preLoaderRoute: typeof MobileLookupPalletRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/lookup-location': {
      id: '/mobile/lookup-location'
      path: '/lookup-location'
      fullPath: '/mobile/lookup-location'
      preLoaderRoute: typeof MobileLookupLocationRouteImport
      parentRoute: typeof MobileRoute
    }
    '/master/sku': {
      id: '/master/sku'
      path: '/master/sku'
      fullPath: '/master/sku'
      preLoaderRoute: typeof MasterSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/location': {
      id: '/master/location'
      path: '/master/location'
      fullPath: '/master/location'
      preLoaderRoute: typeof MasterLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/batch': {
      id: '/master/batch'
      path: '/master/batch'
      fullPath: '/master/batch'
      preLoaderRoute: typeof MasterBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskNo/print': {
      id: '/tasks/$taskNo/print'
      path: '/print'
      fullPath: '/tasks/$taskNo/print'
      preLoaderRoute: typeof TasksTaskNoPrintRouteImport
      parentRoute: typeof TasksTaskNoRoute
    }
    '/master/location/print': {
      id: '/master/location/print'
      path: '/print'
      fullPath: '/master/location/print'
      preLoaderRoute: typeof MasterLocationPrintRouteImport
      parentRoute: typeof MasterLocationRoute
    }
  }
}

interface MobileRouteChildren {
  MobileLookupLocationRoute: typeof MobileLookupLocationRoute
  MobileLookupPalletRoute: typeof MobileLookupPalletRoute
  MobileScanLogRoute: typeof MobileScanLogRoute
  MobileScanMoveRoute: typeof MobileScanMoveRoute
  MobileScanPickRoute: typeof MobileScanPickRoute
  MobileScanPutawayRoute: typeof MobileScanPutawayRoute
  MobileTasksRoute: typeof MobileTasksRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileLookupLocationRoute: MobileLookupLocationRoute,
  MobileLookupPalletRoute: MobileLookupPalletRoute,
  MobileScanLogRoute: MobileScanLogRoute,
  MobileScanMoveRoute: MobileScanMoveRoute,
  MobileScanPickRoute: MobileScanPickRoute,
  MobileScanPutawayRoute: MobileScanPutawayRoute,
  MobileTasksRoute: MobileTasksRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

interface TasksTaskNoRouteChildren {
  TasksTaskNoPrintRoute: typeof TasksTaskNoPrintRoute
}

const TasksTaskNoRouteChildren: TasksTaskNoRouteChildren = {
  TasksTaskNoPrintRoute: TasksTaskNoPrintRoute,
}

const TasksTaskNoRouteWithChildren = TasksTaskNoRoute._addFileChildren(
  TasksTaskNoRouteChildren,
)

interface TasksRouteChildren {
  TasksTaskNoRoute: typeof TasksTaskNoRouteWithChildren
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskNoRoute: TasksTaskNoRouteWithChildren,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface MasterLocationRouteChildren {
  MasterLocationPrintRoute: typeof MasterLocationPrintRoute
}

const MasterLocationRouteChildren: MasterLocationRouteChildren = {
  MasterLocationPrintRoute: MasterLocationPrintRoute,
}

const MasterLocationRouteWithChildren = MasterLocationRoute._addFileChildren(
  MasterLocationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  InventoryRoute: InventoryRoute,
  MobileRoute: MobileRouteWithChildren,
  MoveRoute: MoveRoute,
  MovementsRoute: MovementsRoute,
  OutboundRoute: OutboundRoute,
  PutawayRoute: PutawayRoute,
  TasksRoute: TasksRouteWithChildren,
  MasterBatchRoute: MasterBatchRoute,
  MasterLocationRoute: MasterLocationRouteWithChildren,
  MasterSkuRoute: MasterSkuRoute,
  PalletPalletIdRoute: PalletPalletIdRoute,
  PalletCreateRoute: PalletCreateRoute,
  PalletPrintBatchRoute: PalletPrintBatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
